### ISSUE TITLE
Path must be a string. Received ' + inspect(path)

### ISSUE THREAD

**Issue by justinhough** [patrickarlt/acetate#63]
With a fresh install of acetate in another project and from the `acetate-cli-sample` I get the following errors:

```
$ acetate build
/Desktop/acetate-cli-sample-master/node_modules/acetate/lib/cli
path.js:7
   throw new TypeError('Path must be a string. Received ' + inspect(path));
   ^

TypeError: Path must be a string. Received undefined
   at assertPath (path.js:7:11)
   at Object.resolve (path.js:1146:7)
   at Object.run (/Desktop/acetate-cli-sample-master/node_modules/acetate/lib/cli.js:105:29)
   at /usr/local/lib/node_modules/acetate-cli/bin/acetate.js:15:14
   at /usr/local/lib/node_modules/acetate-cli/node_modules/resolve/lib/async.js:44:21
   at ondir (/usr/local/lib/node_modules/acetate-cli/node_modules/resolve/lib/async.js:187:31)
   at /usr/local/lib/node_modules/acetate-cli/node_modules/resolve/lib/async.js:153:39
   at onex (/usr/local/lib/node_modules/acetate-cli/node_modules/resolve/lib/async.js:93:22)
   at /usr/local/lib/node_modules/acetate-cli/node_modules/resolve/lib/async.js:24:18
   at FSReqWrap.oncomplete (fs.js:111:15)
```

Running node `v7.1.0` and npm `3.10.8`.

These are the versions of acetate I am running on the project:
```
"acetate": "^1.1.1",
"acetate-cli": "^1.0.1",
```

**Comment by paulcpederson** [comment]
@patrickarlt I think this is due to the CLI not setting defaults properly. If you don't declare a `config` from the CLI, it is undefined. If you add `--config acetate.config.js` to the script it works fine. 

Further, aliases also don't get set properly. So using `--config acetate.config.js` works, but using `--c acetate.config.js`. These bugs are most likely to do with how you've implemented the CLI flag parsing with yargs.
